### ISSUE TITLE
Stackalloc here is dangerous

### ISSUE THREAD

**Issue by davidfowl** [timiskhakov/ExploringSpansAndIOPipelines#1]
https://github.com/timiskhakov/ExploringSpansAndPipelines/blob/9ca3cafdf1af672dedf5f1a4076dbc272e1ceba1/ExploringSpansAndPipelines.Core/Parsers/FileParserSpansAndPipelines.cs#L68

This could result in a stackoverflow (if the line is too long). You want to stack alloc only if the length is reasonably small (say 1-256 bytes), anything above that you can use the memory pool, or use the SequenceReader to parse the ReadOnlySequence.

**Comment by timiskhakov** [comment]
Correct, in this demo project I completely (and purposely) ignore long lines as I have a set of predetermined data to keep things and code simple. Added a note on the line's maximum length to the blog post.

Thanks for pointing this out and suggesting possible solutions. I have some ideas for using SequenceReader to solve the problem in general.

**Comment by davidfowl** [comment]
Can you add a failure if it's longer than the amount you expect? Or truncate lines longer than 126/256 bytes? At least then it would be in a comment and reflected in the code.

**Comment by timiskhakov** [comment]
Sure, that's a no-brainer. I [added](https://github.com/timiskhakov/ExploringSpansAndPipelines/pull/2) a failure if the line is longer than I expect.

**Comment by davidfowl** [comment]
Don't forget to update the blog post

**Comment by timiskhakov** [comment]
Aaand it's done.

I really appreciate that you find time to check out what's happening in the community 👍
