### ISSUE TITLE
Project RecordParser to automate LineParser generation

### ISSUE THREAD

**Issue by leandromoh** [timiskhakov/ExploringSpansAndIOPipelines#6]
Hi, I read [your article](https://timiskhakov.github.io/posts/exploring-spans-and-pipelines.html) about how to use span to read files with zero allocation and I find it very releated to [my project record parser](https://github.com/leandromoh/RecordParser) which is basically a "line parser" which build using the line/fine configurations. It generates using expression tree feature the code you would handwriting yourself **using span and all the boilerplate**.

It offers builders for read/write files of type delimited (csv, tsv, etc) and fixed-length (cobol, bank stuffs, etc).

anyway, just sharing because I see synergy and may find it interesting in your projects

example:
```c#
[Fact]
public void Given_value_using_standard_format_should_parse_without_extra_configuration()
{
    var reader = new VariableLengthReaderBuilder<(string Name, DateTime Birthday, decimal Money, Color Color)>()
        .Map(x => x.Name, indexColumn: 0)
        .Map(x => x.Birthday, 1)
        .Map(x => x.Money, 2)
        .Map(x => x.Color, 3)
        .Build(";");
  
    var result = reader.Parse("foo bar baz ; 2020.05.23 ; 0123.45; LightBlue");
  
    result.Should().BeEquivalentTo((Name: "foo bar baz",
                                    Birthday: new DateTime(2020, 05, 23),
                                    Money: 123.45M,
                                    Color: Color.LightBlue));
}
```

**Comment by timiskhakov** [comment]
Hi Leandro, thank you for sharing the library, it looks very interesting! I'll definitely take a closer look at it. For now I did some quick benchmarks, and results are quite good: 
```
|                  Method |       Mean |    Error |   StdDev |      Gen 0 |      Gen 1 |     Gen 2 | Allocated |
|------------------------ |-----------:|---------:|---------:|-----------:|-----------:|----------:|----------:|
|              FileParser | 1,016.6 ms | 14.04 ms | 13.14 ms | 82000.0000 | 29000.0000 | 5000.0000 | 375.43 MB |
|         FileParserSpans |   815.0 ms |  6.59 ms |  6.17 ms | 45000.0000 | 15000.0000 | 4000.0000 | 230.81 MB |
| FileParserSpansAndPipes |   557.0 ms |  4.24 ms |  3.96 ms | 13000.0000 |  5000.0000 | 2000.0000 |  78.73 MB |
|      FileParserImproved |   347.1 ms |  5.65 ms |  5.28 ms | 13000.0000 |  5000.0000 | 2000.0000 |  78.74 MB |
|        FileRecordParser |   594.0 ms |  5.90 ms |  5.52 ms | 15000.0000 |  7000.0000 | 3000.0000 |  78.76 MB |
```

(Sorry for the names of all these parsers, naming is hard 😅)

The `FileRecordParser` class looks the same as `FileParserSpansAndPipes` in the post, but I changed its private `Parse` method into something like this (hopefully, I use the library correctly):
```csharp
public class RecordParser : IFileParser
{
    // Same stuff as in FileParserSpansAndPipes.cs
    // ...

    private static readonly IVariableLengthReader<(Guid, string, Genres, DateTime, int, bool)> Reader =
        new VariableLengthReaderSequentialBuilder<(Guid Id, string Name, Genres Genre, DateTime ReleaseDate, int Rating, bool HasMultiplayer)>()
            .Map(x => x.Id)
            .Map(x => x.Name)
            .Map(x => x.Genre)
            .Map(x => x.ReleaseDate)
            .Map(x => x.Rating)
            .Map(x => x.HasMultiplayer)
            .Build("|");

    private static Videogame Parse(ReadOnlySpan<byte> bytes)
    {
        Span<char> chars = stackalloc char[bytes.Length];
        Encoding.UTF8.GetChars(bytes, chars);

        var (id, name, genre, releaseDate, rating, hasMultiplayer) = Reader.Parse(chars);
        return new Videogame
        {
            Id = id,
            Name = name,
            Genre = genre,
            ReleaseDate = releaseDate,
            Rating = rating,
            HasMultiplayer = hasMultiplayer
        };
    }
}
```

I reckon it's a bit hard to beat `FileParserImproved` since it doesn't spend time on converting `ReadOnlySpan<byte>` into `Span<char>`, instead it [works](https://timiskhakov.github.io/posts/exploring-spans-and-pipelines-revisited) with bytes directly. `RecordParser`'s API is quite clear, but, of course, there is a chance that I missed something critical configuring it.

By the way, someone in a Reddit thread where I posted a link to my blog post mentioned their CSV parser [Cursively](https://github.com/airbreather/Cursively). They also did [some benchmarks](https://www.reddit.com/r/dotnet/comments/dpm1zp/exploring_spans_and_pipelines/f60eawh/) and posted results showing that it works really fast, albeit on CSV files only. It might be worth to check out the parser nonetheless.

**Comment by leandromoh** [comment]
> I reckon it's a bit hard to beat FileParserImproved since it doesn't spend time on converting ReadOnlySpan<byte> into Span<char>, instead it works with bytes directly. 

wow, I have not seen this guy `FileParserImproved`! Looks interesting. In fact, work directly with bytes can't be beat LOL, but of course with have the trade off of be less flexible since we have to define each "byte parser method" manually, and of course this will be very especific since it will work with a specific encode (Utf8 in your example), does not support `CultureInfo`, and custom format for some types (e.g., `DateTime`).

In this sense, use framework Parse methods looks to have a good cost benefit between perfomance/simplicity/flexibility (provided by framework). 

> API is quite clear

Happy to hear it! That was the intented, offers a simple clean API but that also allows user totally customize it using lambdas.

> there is a chance that I missed something critical configuring it.

You almost get it 100%. the input type does not require a tuple, you could have use `Videogame` directly,  
It of course would have avoided some allocations/operations for each line.  
Could you paste a new benchmark with follow adjust?

instead of 
```c#
new VariableLengthReaderSequentialBuilder<(Guid Id, string Name, Genres Genre, DateTime ReleaseDate, int Rating, bool HasMultiplayer)>()
```

you could just write

```c#
new VariableLengthReaderSequentialBuilder<Videogame>()
```

About Cursively, I took it a bref look, and cant find example of configuring entity parser (define columns and its positions, as well customized parsing). It is really sad that people can do awesome works be really lack examples of use.

**Comment by timiskhakov** [comment]
> In fact, work directly with bytes can't be beat LOL, but of course with have the trade off of be less flexible since we have to define each "byte parser method" manually, and of course this will be very especific since it will work with a specific encode (Utf8 in your example), does not support `CultureInfo`, and custom format for some types (e.g., `DateTime`).

Agreed, good point 👍 

> You almost get it 100%. the input type does not require a tuple, you could have use `Videogame` directly,
> It of course would have avoided some allocations/operations for each line.
> Could you paste a new benchmark with follow adjust?

That's cool! It also eliminates a lot of typing. Here is a new benchmark result:
```
|                  Method |       Mean |    Error |   StdDev |      Gen 0 |      Gen 1 |     Gen 2 | Allocated |
|------------------------ |-----------:|---------:|---------:|-----------:|-----------:|----------:|----------:|
|              FileParser | 1,017.3 ms | 16.30 ms | 15.25 ms | 82000.0000 | 28000.0000 | 5000.0000 | 375.41 MB |
|         FileParserSpans |   815.1 ms | 12.98 ms | 11.50 ms | 44000.0000 | 14000.0000 | 3000.0000 |  230.8 MB |
| FileParserSpansAndPipes |   555.5 ms |  2.16 ms |  2.02 ms | 13000.0000 |  5000.0000 | 2000.0000 |  78.74 MB |
|      FileParserImproved |   347.8 ms |  4.51 ms |  3.76 ms | 13000.0000 |  5000.0000 | 2000.0000 |  78.74 MB |
|        FileRecordParser |   594.0 ms |  9.19 ms |  8.15 ms | 15000.0000 |  7000.0000 | 3000.0000 |  78.77 MB |
```
So, now I changed the `FileRecordParser` as follows:
```csharp
public class FileRecordParser : IFileParser
{
    // Same stuff as in FileParserSpansAndPipes.cs
    // ...

    private static readonly IVariableLengthReader<Videogame> Reader = new VariableLengthReaderSequentialBuilder<Videogame>()
        .Map(x => x.Id)
        .Map(x => x.Name)
        .Map(x => x.Genre)
        .Map(x => x.ReleaseDate)
        .Map(x => x.Rating)
        .Map(x => x.HasMultiplayer)
        .Build("|");

    private static Videogame Parse(ReadOnlySpan<byte> bytes)
    {
        Span<char> chars = stackalloc char[bytes.Length];
        Encoding.UTF8.GetChars(bytes, chars);

        return Reader.Parse(chars);
    }
}
```
Seems like using `Videogame` instead of a `ValueTuple` won't reduce the number of allocations. My guess is that it's due to the fact that an instance of `Videogame` has to be created somewhere anyway; either way it's happening in `FileRecordParser` or in the library.

**Comment by timiskhakov** [comment]
@leandromoh as there is nothing actionable left in here, I'm closing the issue for now. However, feel free to comment or reopen it if something new comes up.

**Comment by leandromoh** [comment]
@timiskhakov sorry for the late reply. About the ValueTuple did not reduce the number of allocations, of course it create less value type instances on stack, but benchmarkdotnet probably count just heap metrics :/ 

> However, feel free to comment or reopen it if something new comes up.

No problem! Thanks for your time
